name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Setup Gradle Wrapper
      run: gradle wrapper --gradle-version 8.8

    - name: Execute Unit Tests
      run: ./gradlew test -i
